server {
    listen __PORT__;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    types {
        text/html                         html;
        application/vnd.android.package-archive apk;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
